apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graphql-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pick-your-adventure
        role: master
        tier: backend
    spec:
      containers:
      - name: graphql-server
        image: gcr.io/test-project-196319/adventure-backend:1.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8181